name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: clamav-devel
      run: sudo apt install -y libclamav-dev
    - name: pre-pare
      run: aclocal && autoconf && autoheader && libtoolize && automake --add-missing && autoreconf --install --force
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
